### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by oscargullberg** [jahed/agility#7]
In Chrome, desktop notifications are no longer allowed on insecure sites; there's a deprecation warning in the console on http://oss.jahed.io/agility/timer.html suggesting to host on https instead. Github Pages should be a viable option for this :)

https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

**Comment by jahed** [comment]
Sadly, GitHub Pages doesn't support HTTPS on custom domains, the only solution right not is to move all of my project pages back to jahed.github.io (right now it's oss.jahed.io).

I'll consider moving over and setting up some redirects since it doesn't look like GitHub is planning to support HTTPS on custom domains any time soon.

The downside is that I have no control over jahed.github.io so, I won't be able to set up redirects if GitHub did start supporting it and I wanted to go back to a custom domain.

**Comment by jahed** [comment]
One solution to this is to enable Cloudflare's CDN with Flexible SSL. I already use Cloudflare as the name server, but disabled the CDN on oss.jahed.io since I'm using Strict SSL right now.

Since GitHub serves a *.github.io certifcate, the SSL connection fails when trying to connect via oss.jahed.io. Disabling strict mode will disable this verification step.

**Strict SSL**
```
User ---SSL--> Cloudflare ---SSL--> GitHub
```

**Flexible SSL**
```
User ---SSL--> Cloudflare ---Plain--> GitHub
```

However, I don't want to do this since the change will be global across all my subdomains. Having plain traffic defeats the point of all these recent clamp downs on HTTPS connections on web browsers. It's more of a hack if anything.

**Comment by mhanberg** [comment]
Hi! First would like to thank you for this tool, my team and I use it everyday. 

You should try moving it to Netlify (netlify.com). Has full HTTPS support and a free tier. 

Thanks!

**Comment by jahed** [comment]
Thanks, I'll look into it.

**Comment by jahed** [comment]
I've moved the project over to Netlify. Thanks for the recommendation @mhanberg!

I've also set up redirects from `oss.jahed.io/agility/.*` to `agility.jahed.io/.*`. If anything's not working let me know.

Since Netlify acts as a build server, I can remove the Travis configuration. I'll leave this ticket open until that's done.

**Comment by mhanberg** [comment]
@jahed no problem! Thanks!
